/*
 * generated by Xtext
 */
package com.newdigate.soa.entitydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EntityLanguageUiModule extends com.newdigate.soa.entitydsl.ui.AbstractEntityLanguageUiModule {
	public EntityLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
