/*
 * generated by Xtext
 */
package com.newdigate.soa.entitydsl.ui.contentassist

import com.newdigate.soa.entitydsl.ui.contentassist.AbstractEntityLanguageProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class EntityLanguageProposalProvider extends AbstractEntityLanguageProposalProvider {
}
