/*
 * generated by Xtext
 */
package com.newdigate.soa.entitydsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class EntityLanguageStandaloneSetup extends EntityLanguageStandaloneSetupGenerated{

	public static void doSetup() {
		new EntityLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

