/*
 * generated by Xtext
 */
package com.newdigate.soa.entitydsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EntityLanguageRuntimeModule extends com.newdigate.soa.entitydsl.AbstractEntityLanguageRuntimeModule {

}
